name: build docker image 

on: 
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  IMAGE_NAME: justeat_code_test

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF:11}
          echo "$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
      
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # lowercase IMAGE_ID
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID:${{ env.version }}
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push --all-tags $IMAGE_ID