name: Static analysis & Unit testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - ".github/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Pylint
        working-directory: ./
        run: |
          make lint

      - name: Unittest with coverage report
        run: |
          make test-all-report